### ISSUE TITLE
Error on 'Make' 

### ISSUE THREAD

**Issue by JacksonAll** [Sysinternals/ProcMon-for-Linux#110]
After a successful build and running make I receive these errors: 

Consolidate compiler generated dependencies of target test-sqlite3-storage
[ 96%] Building CXX object src/storage/CMakeFiles/test-sqlite3-storage.dir/test_sqlite3_storage_engine.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/jacks/Procmon-for-Linux/build/_deps/catch2-src/single_include/catch2/catch.hpp:6113,
                 from /home/jacks/Procmon-for-Linux/src/storage/test_sqlite3_storage_engine.cpp:5:
/home/jacks/Procmon-for-Linux/build/_deps/catch2-src/single_include/catch2/catch.hpp:8749:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 8749 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/jacks/Procmon-for-Linux/build/_deps/catch2-src/single_include/catch2/catch.hpp:6113,
                 from /home/jacks/Procmon-for-Linux/src/storage/test_sqlite3_storage_engine.cpp:5:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/jacks/Procmon-for-Linux/src/storage/test_sqlite3_storage_engine.cpp:5:
/home/jacks/Procmon-for-Linux/build/_deps/catch2-src/single_include/catch2/catch.hpp:8808:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 8808 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [src/storage/CMakeFiles/test-sqlite3-storage.dir/build.make:76: src/storage/CMakeFiles/test-sqlite3-storage.dir/test_sqlite3_storage_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2594: src/storage/CMakeFiles/test-sqlite3-storage.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by MarioHewardt** [comment]
Hi - Thanks for reporting this issue. What distribution are you compiling on? Please note that at the moment Procmon for Linux only works on Ubuntu 20.04.

**Comment by slyles1001** [comment]
I bumped the version of catch2 to the latest 2.x and the build finished, and procmon ran:
```
# Fetch Catch2 testing framework.
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v2.13.10
)
```

![image](https://github.com/Sysinternals/ProcMon-for-Linux/assets/17685289/5483968d-c259-467c-a5a4-f5435dbef298)
